package cli

import (
	"fmt"
	"sort"
	"strings"
)

// HelpGuide derives offline documentation from the exact terminal metadata and
// fixed Bundle views. It performs no execution or project lookup.
func HelpGuide(reference bool) (string, error) {
	var out strings.Builder
	out.WriteString("<!-- Generated by go run ./tools/helpdocs; edit command metadata and fixed help views. -->\n# YSS CLI 离线帮助与案例\n\n")
	out.WriteString("终端默认中文摘要；管道和重定向保留原结果。`--human` 强制中文，`--json` 保持 outputVersion=1 / protocolVersion=1，二者互斥。`--json --diagnostics` 仅在失败时附加顶层诊断，不改变 `result`。帮助优先处理并始终为文本；它不读取项目、写入文件或访问网络。\n\n")
	out.WriteString("诊断区分已确认原因、可能原因和待核验事项；处理命令标记只读、写入或联网。版本要求没有可核验记录时显示‘尚未登记’；远程确认使用 `yss upgrade --check`。\n\n")
	root, err := renderHelp(nil)
	if err != nil {
		return "", err
	}
	fmt.Fprintf(&out, "## 入口导航\n\n```text\n%s\n```\n\n", root)
	for _, name := range tutorialTopics {
		content, err := renderTutorial(name)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&out, "## 教程：%s\n\n```text\n%s\n```\n\n", name, content)
	}
	out.WriteString("## 案例材料与验证\n\n公开示例的占位符须替换为真实目录、合同、完整基线和当前证据。批准、独立审查和外部操作由对应负责人取得。源码中的 `internal/cli/testdata/tutorial`、日常测试和治理测试是内部案例，不构成业务批准。\n\n案例实际执行结果记录在候选验证报告，区分通过、预期阻断和未执行。CLI 核验消费已有测试记录，不代替执行测试。阶段计划重定向保存原始结果，不添加 `--json`；envelope 不能当作 `--plan-file` 输入。项目计划用 `--out` 保存。\n\n")
	keys := []string{}
	for key := range commands {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	out.WriteString("## 命令参考\n\n| 命令 | 用途 | 示例入口 |\n| --- | --- | --- |\n")
	for _, key := range keys {
		fmt.Fprintf(&out, "| `%s` | %s | `yss help examples %s` |\n", key, strings.ReplaceAll(commands[key].help.summary, "|", "\\|"), key)
	}
	if reference {
		for _, key := range keys {
			content, err := renderHelp(strings.Fields(key))
			if err != nil {
				return "", err
			}
			fmt.Fprintf(&out, "\n### %s\n\n```text\n%s\n```\n", key, content)
		}
		for _, code := range errorCodes {
			content, err := renderErrorHelp(code)
			if err != nil {
				return "", err
			}
			fmt.Fprintf(&out, "\n### 错误 %s\n\n```text\n%s\n```\n", code, content)
		}
	} else {
		content, _ := renderErrorHelp("")
		fmt.Fprintf(&out, "\n## 错误索引\n\n```text\n%s\n```\n", content)
	}
	return out.String(), nil
}
